---
title: 'Assignment 2: Gapminder Exploration'
author: "Kyle Wlodarczyk"
date: "September 19, 2019"
output: 
  html_document:
    df_print: paged
    toc: yes
    number_sections: yes
    theme: cerulean

---

```{r, warning = FALSE, echo = FALSE}
library(gapminder)
library(tidyverse)
library(scales)
library(tsibble)

```

# Exercise 1: Basic dplyr

## Exercise 1.1

```{r, echo = FALSE}
gapminder %>%
  filter(country == "Poland" | country == "Austria" | country == "Switzerland",
         year >= 1970 & year < 1980)

```

## Exercise 1.2

```{r, echo = FALSE}
gapminder %>%
  filter(country == "Poland" | country == "Austria" | country == "Switzerland",
         year >= 1970 & year < 1980) %>%
  select(country, gdpPercap)

```

## Exercise 1.3

```{r, echo = FALSE}
gapminder %>%
  filter(lifeExp < diff(lifeExp, 1))
```

## Exercise 1.4

```{r, echo = FALSE}
gapminder %>%
  select(country, gdpPercap) %>%
  arrange(desc(gdpPercap)) %>%
  top_n(3, gdpPercap)
  
  
```

## Exercise 1.5

```{r, echo = FALSE}
gapminder %>%
  filter(country == "Canada") %>%
  ggplot(aes(lifeExp, gdpPercap)) +
  geom_point(alpha = 1) + 
  scale_y_log10("GDP per Capita") +
  xlab("Life Expectancy") +
  theme_bw()

```

# Exercise 2: Explore individual variables with dplyr

```{r, echo = FALSE}

```

# Exercise 3: Explore various plot types

```{r, echo = FALSE}

```

